class_name Python
extends Node


static func make_indent(content: Array, size: int) -> String:
	var indent := " ".repeat(size)
	return "\n".join(content.map(func(x: String) -> String: return indent + x))


static func generate_header(ap_name: String) -> String:
	return "\n".join([
		"# APWorld for %s" % ap_name,
		"#",
		"# This file is automatically generated by ap_gen_tool version 2.0.",
		"# For more information: https://github.com/ArchipelagoDoom/ap_gen_tool",
		""
	])


static func generate_id1_import(import: String) -> String:
	return "\n".join([
		"try:",
		"    from worlds._id1common %s" % import,
		"except ImportError:",
		"    from .id1common %s" % import,
		""
	])

  

static func generate_init(world: World, options: Array) -> PackedByteArray:
	Status.set_task("Generating init script")
	var cn := world.game.ap_class_name as String
	var code := [
		generate_header(world.game.ap_name),
		"import typing",
		"",
		"import BaseClasses as AP  # noqa: N814",
		generate_id1_import("import id1CommonWorld"),
		"from worlds.AutoWorld import WebWorld",
		"",
		"from .options import %sOptionGroups, %sOptions" % [cn, cn],
		"",
		"game_name = \"%s\"" % world.game.ap_name.json_escape(),
		"",
		"",
		"class %sLocation(AP.Location):" % cn,
		"    game: str = game_name",
		"",
		"",
		"class %sItem(AP.Item):" % cn,
		"    game: str = game_name",
		"",
		"",
		"class %sWeb(WebWorld):" % cn,
		"    option_groups = %sOptionGroups" % cn,
		"    rich_text_options_doc = True",
		"    bug_report_page = \"https://github.com/ArchipelagoDoom/APDoom/issues\"",
		"    theme = \"dirt\"",
		"    tutorials = []  # Not included",
		"",
		"",
		"class %sWorld(id1CommonWorld, import_data=(__name__, \"%s.data.json\")):" % [cn, world.game.short_name.json_escape()],
		"    \"\"\"",
		make_indent(world.game.world_info.description, 4),
		"    \"\"\"",
		"    game = game_name",
		"    options_dataclass = %sOptions" % cn,
		"    options: %sOptions  # type: ignore" % cn,
		"    web = %sWeb()" % cn,
		"    required_client_version = (0, 6, 3)  # APDoom version 2.0.0",
		"",
		make_indent(WorldOptions.add_hook(world, "class", options), 4),
		"    extra_connection_requirements = {",
		"        \"deathlogic\": lambda self: self.options.allow_death_logic.value == 1,",
		"        \"trick_basic\": lambda self: self.options.trick_difficulty.value >= 1,",
		"        \"trick_pro\": lambda self: self.options.trick_difficulty.value >= 2,",
		"        \"trick_extreme\": lambda self: self.options.trick_difficulty.value >= 3,",
		make_indent(WorldOptions.add_hook(world, "extra_connection_requirements", options), 8),
		"    }",
		"",
		
		"    def create_item(self, name: str) -> %sItem:" % cn,
		"        item_id = self.item_name_to_id[name]",
		"        item_data = self.item_table[item_id]",
		"        classification = item_data.classification",
		"",
		make_indent(WorldOptions.add_hook(world, "create_item", options), 8),
		"        return %sItem(name, classification, item_id, self.player)" % cn,
		"",
		
		"    def generate_early(self) -> None:",
		"        self.init_episodes()",
		"",
		make_indent(WorldOptions.add_hook(world, "generate_early", options), 8),
		
		"    def create_regions(self) -> None:",
		"        self.construct_regions()",
		"        self.make_regions(location_type=%sLocation)" % cn,
		"",
		make_indent(WorldOptions.add_hook(world, "create_regions", options), 8),

		"    def set_rules(self) -> None:",
		"        self.make_rules()",
		"",
		make_indent(WorldOptions.add_hook(world, "set_rules", options), 8),

		"    def create_items(self) -> None:",
		"        self.place_level_complete_items(item_type=%sItem)" % cn,
		"",
		"        itempool = self.construct_base_item_pool()",
		"        location_count = len(self.multiworld.get_unfilled_locations(self.player))",
		"        def pop_from_pool(name: str) -> str | None:",
		"            return itempool.pop(itempool.index(name)) if name in itempool else None",
		"",
		"        # Give starting levels immediately",
		"        map_items = [pop_from_pool(map_name) for map_name in self.starting_levels]",
		"        [self.multiworld.push_precollected(self.create_item(n)) for n in map_items if n is not None]",
		"",
		make_indent(WorldOptions.add_hook(world, "create_items", options), 8),
		"        # Fill remainder with filler, and submit",
		"        self.fill_item_pool(itempool, location_count)",
		"        self.multiworld.itempool.extend(self.create_item(item) for item in itempool)",
		"",

		"    def fill_slot_data(self) -> dict[str, typing.Any]:",
		"        slot_data = super().fill_slot_data()",
		"",
		make_indent(WorldOptions.add_hook(world, "fill_slot_data", options), 8),
		"        return slot_data",
		"",
	]
	
	return "\n".join(code).to_ascii_buffer()


static func generate_options(world: World, levels: Array, options: Array) -> PackedByteArray:
	Status.set_task("Generating options script")
	var py_options := []
	
	WorldOptions.add_default_options(world, levels, py_options)
	WorldOptions.add_py_options(world, options, py_options)
	
	var cn := world.game.ap_class_name as String
	var code := [
		generate_header(world.game.ap_name),
		"# Options docstrings may exceed the line length limit.",
		"# ruff: noqa: E501",
		"",
		"from dataclasses import dataclass",
		"",
		"import Options as BaseOptions",
		generate_id1_import("import options as id1Options  # noqa: N812"),
		"",
		""
	]
	
	for option: Dictionary in py_options:
		code.push_back(PyOptions.generate_py_option_class(option))
	
	code.push_back("@dataclass")
	code.push_back("class %sOptions(id1Options.id1CommonOptions):" % cn)
	
	for option: Dictionary in py_options:
		code.push_back("    %s" % PyOptions.generate_data_class(option))
	
	code.push_back("")
	code.push_back("")
	
	var option_groups := {
		"Episodes to Play": [],
		"Goal Options": [],
		"Difficulty Options": [],
		"Randomizer Options": [],
		"Item & Location Options": []
	}
	
	var group_order := ["Episodes to Play", "Goal Options", "Difficulty Options", "Randomizer Options"]
	
	for option: Dictionary in py_options:
		if option.has("option_group") and not option_groups.has(option.option_group):
			option_groups[option.option_group] = []
			group_order.push_back(option.option_group)
	
	group_order.push_back("Item & Location Options")
	
	option_groups["Goal Options"].push_back("id1Options.Goal")
	option_groups["Randomizer Options"].push_back("BaseOptions.ProgressionBalancing")
	option_groups["Randomizer Options"].push_back("BaseOptions.Accessibility")
	if world.game.settings.get("check_sanity", false):
		option_groups["Randomizer Options"].push_back("id1Options.CheckSanity")
	option_groups["Randomizer Options"].push_back("id1Options.RandomMonsters")
	option_groups["Randomizer Options"].push_back("id1Options.RandomPickups")
	option_groups["Randomizer Options"].push_back("id1Options.RandomMusic")
	if world.game.iwad != "HERETIC.WAD":
		option_groups["Randomizer Options"].push_back("id1Options.FlipLevels")
	else:
		option_groups["Randomizer Options"].push_back("BaseOptions.Removed");
	for option: Dictionary in py_options:
		if option.has("option_group"):
			option_groups[option.option_group].push_back(PyOptions.get_class_name(option))
	option_groups["Difficulty Options"].push_back("id1Options.TrickDifficulty")
	option_groups["Difficulty Options"].push_back("id1Options.AllowDeathLogic")
	option_groups["Difficulty Options"].push_back("id1Options.ResetLevelOnDeath")
	option_groups["Difficulty Options"].push_back("BaseOptions.DeathLink")
	option_groups["Difficulty Options"].push_back("id1Options.EnergyLink")
	
	code.push_back("%sOptionGroups = [" % world.game.ap_class_name)
	for group: String in group_order:
		if option_groups[group].is_empty():
			continue
		
		code.push_back("    BaseOptions.OptionGroup(\"%s\", [" % group.json_escape())
		for option_class: String in option_groups[group]:
			code.push_back("        %s," % option_class)
		
		if group == group_order.back():
			code.push_back("    ], start_collapsed=True),")
		else:
			code.push_back("    ]),")
	
	code.push_back("]")
	code.push_back("")
	return "\n".join(code).to_ascii_buffer()
