name: Create release
run-name: Release build ${{ inputs.version-number }}
on:
  workflow_dispatch:
    inputs:
      version-number:
        description: Version number
        required: true
        type: string
        default: v1.0

env:
  GAME_NAME: ap_gen_tool

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform: [
          { os: "windows", target: "Windows Desktop", ext: "exe" },
          { os: "linux", target: "Linux", ext: "x86_64" }
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Export tools
        uses: appsinacup/action_export_godot_game@main
        with:
          godot-version: 4.7.2-stable
          game-name: ${{ env.GAME_NAME }}
          platform-name: ${{ matrix.platform.target }}
      
      - name: Move built files
        run: |
          mv build/${{ env.GAME_NAME }} export/${{ matrix.platform.os }}/${{ env.GAME_NAME }}.${{ matrix.platform.ext }}
          mv build/${{ env.GAME_NAME }}.pck export/${{ matrix.platform.os }}/${{ env.GAME_NAME }}.pck
      
      - name: Check tree
        run: tree -a .

      - name: Run zip script
        working-directory: ./export
        run: ./package-${{ matrix.platform.os }}.sh
      
      - name: Upload zip
        uses: actions/upload-artifact@v7
        with:
          name: ap-gen-tool-${{ matrix.platform.os }}.zip
          archive: false
          path: ./export/${{ matrix.platform.os }}/ap-gen-tool-${{ matrix.platform.os }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: "Push tag"
        uses: EndBug/latest-tag@latest
        with:
          ref: ${{ inputs.version-number }}
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          name: Release ${{ inputs.version-number }}
          tag_name: ${{ inputs.version-number }}
          files: |
            dist/ap_gen_tool_windows.zip
            dist/ap_gen_tool_linux.zip

