name: Create release
run-name: Release build
on: [workflow_dispatch]

env:
  GAME_NAME: ap_gen_tool

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform: [
          { name: "Windows Desktop" },
          { name: "Linux" }
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Export tools
        uses: appsinacup/action_export_godot_game@main
        with:
          godot-version: 4.7.2-stable
          game-name: ${{ env.GAME_NAME }}
          platform-name: ${{ matrix.platform }}

      - name: Run zip script
        run: bash export/package.sh
      
      - name: Upload linux zip
        uses: actions/upload-artifact@v7
        with:
          path: export/linux/ap-gen-tool-linux.zip
       
      - name: Upload windows zip
        uses: actions/upload-artifact@v7
        with:
          path: export/windows/ap-gen-tool-windows.zip

