name: Create release
run-name: Release build
on: [workflow_dispatch]

env:
  GAME_NAME: ap_gen_tool

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform: [
          { name: "Windows Desktop", script: "package-windows.sh", result: "ap-gen-tool-windows.zip" },
          { name: "Linux", script: "package-linux.sh", result: "ap-gen-tool-linux.zip" }
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Export tools
        uses: appsinacup/action_export_godot_game@main
        with:
          godot-version: 4.7.2-stable
          game-name: ${{ env.GAME_NAME }}
          platform-name: ${{ matrix.platform.name }}

      - name: Run zip script
        run: bash export/${{ matrix.platform.script }}
      
      - name: Upload zip
        uses: actions/upload-artifact@v7
        with:
          path: export/${{ matrix.platform.result }}

